### ISSUE TITLE
will plan an enhancement for encoding the toml tree?

### ISSUE THREAD

**Issue by betterjun** [pelletier/go-toml#121] opened 2016-12-29 01:28 UTC
I think it's valuable to do that, many thanks!

**Comment by pelletier** [comment] 2016-12-29 18:47
Hi, do you mind elaborating on the enhancements you have in mind?

**Comment by tgulacsi** [comment] 2017-01-07 08:09
I have two issues with thee current String() method: panics and not reproducible, 'cause of map ordering.
Either the encoder should sort thee map keys, or store the key order, and use that.

**Comment by pelletier** [comment] 2017-03-02 17:22
@betterjun closing this since https://github.com/pelletier/go-toml/pull/133 has been merged. Feel free to reopen and elaborate if you had other improvements in mind.

**Closed by pelletier** 2017-03-02 17:22 UTC
Labels: question
