### ISSUE TITLE
Question: The toml I am working to support seems to preclude the use of unmarshal...

### ISSUE THREAD

**Issue by willauld** [pelletier/go-toml#220] opened 2018-03-02 02:36 UTC
Question: The toml I am working to support seems to preclude the use of unmarshal in that it has some groups that may or may not be named. (I don't know the correct terminology here) Example:

Toml file could contain
[SocialSecurity] 
and/or
[SocialSecurity.xxx]

If there is more than one section "[SocialSecurity]" in the file all or all but one will need to have a unique xxx portion. So when they all have this unique string, unmarshalling into a map[string]SocialSecurity works grait. But breaks otherwise. I don't see away around this using unmarshal, am I missing something? Is this clear?
Thanks,
Will

**Comment by willauld** [comment] 2018-04-19 21:57
I’ll dig up the code I had and construct an example for you. 

 

For the toml config language I have,  the user can define group [SocialSecurity], [SocialSecurity.name1], [SocialSecurity.name2]. Essentially, if only one of these groups is defined, no owner name is needed but if two are defined then one or both of the groups must have a name. The desired output structure would have a list of SocialSecurity groups index by name. This work when both groups have a name given. However when one of two groups has no name given, then we get a list of all the components of the unnamed group and the other named group. 

 

So the question was whether there was a way to have a list of groups, maybe with a virtual (generated) index name?

 

I’ll put together an example. 

 

Thanks,

Will

**Comment by willauld** [comment] 2018-04-19 23:37
Sorry this is lame. I’m attaching a toml file for testing and a go file that can be run with go test. The lame part is that it’s not working at all right now. Back when I originally submitted the question it was working but not now. I’m not sure what I am doing wrong. Most of the go code is just defining the data structures. If you can point me to my problem I’ll complete the example case for you. 

 

Thanks,

Will

 

From: Will Auld [mailto:will@auld.com] 
Sent: Thursday, April 19, 2018 2:57 PM
To: 'pelletier/go-toml' <reply@reply.github.com>; 'pelletier/go-toml' <go-toml@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>; 'Will Auld' <will@auld.com>
Subject: RE: [pelletier/go-toml] Question: The toml I am working to support seems to preclude the use of unmarshal... (#220)

 

I’ll dig up the code I had and construct an example for you. 

 

For the toml config language I have,  the user can define group [SocialSecurity], [SocialSecurity.name1], [SocialSecurity.name2]. Essentially, if only one of these groups is defined, no owner name is needed but if two are defined then one or both of the groups must have a name. The desired output structure would have a list of SocialSecurity groups index by name. This work when both groups have a name given. However when one of two groups has no name given, then we get a list of all the components of the unnamed group and the other named group. 

 

So the question was whether there was a way to have a list of groups, maybe with a virtual (generated) index name?

 

I’ll put together an example. 

 

Thanks,

Will

**Comment by willauld** [comment] 2018-04-20 00:17
OK, I figured out what was going on, in the toml file I had:

[iam]
... # stuff

[iam.retiree2]
... # stuff

UnMarshal() does not give an error but does not fill in the structures in this case. If I change the first [iam] to [iam.retiree1] is fills in everything as expected. With this understanding I'll go make a much simpler example that the one I sent.

**Comment by willauld** [comment] 2018-04-20 00:30
OK, here is the example:

`func TestGetExample2(t *testing.T) {

	type Iam struct {
		Name string
	}
	type Family struct {
		Name string
		Iam  map[string]Iam
	}

	document := []byte(`
	name = "Johnson"
	[iam] name = "Will"
	[iam.joe] name = "Joe"
	[iam.sam] name = "Sam"
	`)

	cfg, err := toml.LoadBytes(document)
	if err != nil {
		fmt.Printf("Error: %s\n", err)
	}

	fam := Family{}
	cfg.Unmarshal(&fam)
	fmt.Printf("Family Structure: %#v\n", fam)
}`

If the first "[iam]" is commented out it works as expected. If left as it does not work at all. The case I'd like to have working is with all of these there and the UnMarshal() creating a 'key' for the map enter in the case with no explicit key ( virtual key, joe, sam). 

Whether or not you provide a virtual key like this, it seems there is a bug the way it is working now. 

Thanks!

**Comment by pelletier** [comment] 2019-02-28 22:56
Somehow never realized this was reopened, sorry! Seems like a duplicate of https://github.com/pelletier/go-toml/issues/252

**Closed** 2019-03-01 19:18 UTC
