### ISSUE TITLE
Improve error message for string parsing

### ISSUE THREAD

**Issue by pgundlach** [pelletier/go-toml#858] opened 2023-03-15 19:52 UTC
**Describe the bug**
When I try to read `foo = bar` to a string, I get an error:

```
1| foo = bar
 |       ~~~ incomplete number
```

I think this error message might lead to confusion. 

**To Reproduce**
```go
package main

import (
	"fmt"

	"github.com/pelletier/go-toml/v2"
)

func main() {
	doc := `foo = bar`
	type mystruct struct {
		Foo string
	}
	var mydata mystruct

	err := toml.Unmarshal([]byte(doc), &mydata)
	fmt.Println(err.(*toml.DecodeError).String())

}
```

**Expected behavior**
Since the library knows what kind of data I expect (`Foo` is a `string`), I'd expect an error message such as "could not parse string" or "quotes missing" or something like that.

**Versions**
 - go-toml: github.com/pelletier/go-toml/v2 v2.0.7
 - go: go1.20.1
 - operating system: macOS

**Comment by pgundlach** [comment] 2023-03-16 07:10
I guess this is a duplicate of https://github.com/pelletier/go-toml/issues/413#issuecomment-841651368

**Comment by pelletier** [comment] 2023-03-20 17:59
You're right, that's a duplicate of #413. I'll close this one, but will add a note on the other issue that we should look into using the type of the target to generate an error message.

**Closed as not planned by pelletier** 2023-03-20 17:59 UTC
