### ISSUE TITLE
Inline tables support

### ISSUE THREAD

**Issue by grabarczyk-t** [pelletier/go-toml#105] opened 2016-10-11 08:33 UTC
[Hugo](http://gohugo.io/) website framework, that uses this library, has problems reading [inline tables](https://github.com/toml-lang/toml#user-content-inline-table) in toml files. See https://github.com/spf13/hugo/issues/2554

**Comment by pelletier** [comment] 2016-10-11 12:36
Thank you for your feedback! Inline tables are supported by go-toml. I have tried the snippet you provided in https://github.com/spf13/hugo/issues/2554, and it seems to work fine:

```
$ cat test.toml
my_variable = { key = "value" }
$ cat test.toml | go run cmd/tomll/main.go

[my_variable]
  key = "value"
```

Do you mind providing a reproducible test case?

**Comment by grabarczyk-t** [comment] 2016-10-11 13:02
I don't have any test case, other than the one connected directly to Hugo framework. I created this issue following a request from Hugo issue tracker. 

So it would seem the problem is on the Hugo side. Sorry for creating the issue without checking it first

**Comment by pelletier** [comment] 2016-10-11 13:05
No worries :) I'm closing this issue, but feel free to reopen if it turns out the bug is in go-toml.

**Closed by pelletier** 2016-10-11 13:05 UTC
