### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Khurshid11** [pelletier/go-toml#766] opened 2022-04-28 15:36 UTC
# github.com/pelletier/go-toml
/home/usradmin/go/src/nsdcserverside/src/github.com/pelletier/go-toml/utf8.go:224:10: syntax error: unexpected b10000000, expecting semicolon or newline or )

**Comment by pelletier** [comment] 2022-04-28 15:38
Please fill out the bug report template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior. Including TOML files.

**Expected behavior**
A clear and concise description of what you expected to happen, if other than "should work".

**Versions**
 - go-toml: version (git sha)
 - go: version
 - operating system: e.g. macOS, Windows, Linux

**Additional context**
Add any other context about the problem here that you think may help to diagnose.

**Comment by pelletier** [comment] 2022-05-10 11:14
This looks like spam. Closing.

**Closed as completed by pelletier** 2022-05-10 11:14 UTC
